name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  wasm-js:
    name: Build WasmJs Web
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build WasmJS distribution
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/outputs/apk/release

  ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build iOS framework
        run: ./gradlew :composeApp:iosArm64Test

      - name: Upload iOS Framework
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/bin/iosArm64/releaseFramework

  desktop:
    name: Build Desktop App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build Desktop Application
        run: ./gradlew :composeApp:desktop:build

      - name: Upload Desktop artifact
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/distributions